// Re-export backend schemas for use in frontend (React Query hooks, etc.)
export {
  CreateArticleRequestSchema,
  UpdateArticleRequestSchema,
  ArticleResponseSchema,
  ArticleStatusSchema,
  ContentToneSchema,
  ContentLengthSchema,
  ReadingLevelSchema,
  GenerateArticleRequestSchema,
  GenerateArticleResponseSchema,
  AIGeneratedContentSchema,
  ListArticlesQuerySchema,
  ListArticlesResponseSchema,
  type CreateArticleRequest,
  type UpdateArticleRequest,
  type ArticleResponse,
  type GenerateArticleRequest,
  type GenerateArticleResponse,
  type AIGeneratedContent,
  type ListArticlesQuery,
  type ListArticlesResponse,
} from '@/features/articles/backend/schema';
